apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nvp3m8b0n-python-gitops
  description: This is GitOps manifest for nvp3m8b0n-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=nvp3m8b0n-python
    backstage.io/kubernetes-id: nvp3m8b0n-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-test-organization-jk/nvp3m8b0n-python-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nvp3m8b0n-python
