apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nvp3m8b0n-python-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/nvp3m8b0n-python-gitops